# fly.toml file generated for jr-pocketbase on 2023-02-18T15:32:19-05:00

app = "jr-pocketbase"
kill_signal = "SIGINT"
kill_timeout = 300
processes = []

[env]

[experimental]
  auto_rollback = true

[mounts]
  destination = "/pb/pb_data"
  source = "pb_data"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "5s"
    interval = "15s"
    restart_limit = 0
    timeout = "10s"
